[versions]
annotationsApi = "6.0.53"
appcompat = "1.7.0"
espressoCore = "3.6.1"
fragment = "1.8.1"
grpcAndroid = "1.64.0"
grpcOkhttp = "1.64.0"
grpcProtobufLite = "1.64.0"
guava = "33.0.0-android"
junit = "4.13.2"
junitVersion = "1.2.1"
lifecycleViewmodel = "2.7.0"
material = "1.12.0"
preference = "1.2.1"
protobufGradlePlugin = "0.9.4"
recyclerview = "1.3.2"
recyclerviewSelection = "1.1.0"
roomRuntime = "2.6.1"

[libraries]
annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "annotationsApi" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
grpc-android = { module = "io.grpc:grpc-android", version.ref = "grpcAndroid" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpcProtobufLite" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpcProtobufLite" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleViewmodel" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleViewmodel" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobufGradlePlugin" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-guava = { module = "androidx.room:room-guava", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]

